name: Clojure CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install rlwrap
      run: sudo apt install rlwrap
    
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.1.693
        
    - name: Run tests
      run: clj -X:test
